---
- hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=43200
      
- include: control.yml
- include: database.yml
- include: webserver.yml
- include: loadbalancer.yml
